multiple files changed and added to slackbuild

diff --git a/ffmpeg/ffmpeg.SlackBuild b/ffmpeg/ffmpeg.SlackBuild
--- a/ffmpeg/ffmpeg.SlackBuild
+++ b/ffmpeg/ffmpeg.SlackBuild
@@ -23,9 +23,10 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PRGNAM=ffmpeg
-VERSION=${VERSION:-2.8.3}
+VERSION=${VERSION:-2.8.4}
 BUILD=${BUILD:-1}
-TAG=${TAG:-_dbx}
+TAG=${TAG:-_sfp}
+FREE_PATENTS=${FREE_PATENTS:-'yes'}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -43,18 +44,44 @@ OUTPUT=${OUTPUT:-/tmp}
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
   LIBDIRSUFFIX=""
+  ARCH_OPTS=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
   LIBDIRSUFFIX=""
+  ARCH_OPTS=""
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
+  ARCH_OPTS="--arch=x86_64 --enable-pic"
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
+  ARCH_OPTS=""
 fi
 
-set -e # Exit on most errors
+set -e
+
+# environment sanity checks
+TEXI2HTML=$(which texi2html 2>/dev/null)
+
+if [ "$TEXI2HTML" = "" ]; then
+  echo "Could not find texi2html, you will ned to have true login shell"
+  echo "You will nedd to either use 'su -l' when switching to root or "
+  echo "source the /etc/profile before execute this SlackBuild"
+  exit 1
+fi
+
+# Only use non-free code if we are allowing it:
+if [ ${FREE_PATENTS} != "no" ]; then
+  PATENTS_PARAMS="--enable-openssl \
+                --enable-nonfree \
+                --enable-gpl \
+                --enable-version3"
+else
+  PATENTS_PARAMS="--enable-gnutls \
+                --enable-gpl \
+                --enable-version3"
+fi
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -69,37 +96,42 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-./configure --help
-exit
+# ./configure --help
+# exit
 
-DEPS="--enable-frei0r \
-    --enable-ladspa \
-    --enable-libass \
-    --enable-libbluray \
-    --enable-libbs2b \
-    --enable-libcelt \
-    --enable-libdc1394 \
-    --enable-opencv "
-
-# Your application will probably need different configure flags;
-# these are provided as an example only.
-# Be sure to build only shared libraries unless there's some need for
-# static.
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --sysconfdir=/etc \
-  --localstatedir=/var \
+  --shlibdir=/usr/lib${LIBDIRSUFFIX} \
+  --docdir=/usr/doc/${PRGNAM}-${VERSION} \
   --mandir=/usr/man \
-  --docdir=/usr/doc/$PRGNAM-$VERSION \
+  --disable-debug \
+  --enable-shared \
+  --disable-static \
+  --enable-runtime-cpudetect \
+  --enable-libtheora \
+  --enable-libvorbis \
+  --enable-postproc \
+  --enable-swscale \
+  --enable-x11grab \
+  --enable-avfilter \
   --enable-fontconfig \
   --enable-libcaca \
   --enable-libcdio \
-  ${DEPS} \
-  --build=$ARCH-slackware-linux
-
+  --enable-libssh \
+  --enable-libsmbclient \
+  --enable-opengl \
+  --enable-libfreetype \
+  --enable-libv4l2 \
+  --enable-libwavpack \
+  --enable-libvpx \
+  ${FFMPEG_DEPS} \
+  ${PATENTS_PARAMS} \
+  ${ARCH_OPTS}
+echo ${ARCH_OPTS}
+exit
 # Compile the application and install it into the $PKG directory
 make
 make install DESTDIR=$PKG
